### ISSUE TITLE
Reloading when searching

### ISSUE THREAD

**Issue by KevinZheng0701** [NurMazumder/VideoGameCatalog#7]
Currently when one logs into the website, the isAuthenticated state is always true. This makes it so that it always navigates to the search page. Need to find a solution for this.
Code causing this: Navbar.jsx has a useEffect so when someone navigate to any site, it will force navigation to search page. Need to find a different fix.

**Comment by KevinZheng0701** [comment]
There is a couple of ways we can fix it:
1) Change the default page so it showcase some games and allow user to sign up/login in the navbar.
2) Change it so that once a user is logged in, the default page display something else.
Also need some logic tweaking on when a user is already logged in what happens if they try to log back in again. Also need a way to make a new password if one forgets it.

**Comment by NurMazumder** [comment]
The navbar /search bug has been fixed, now it should allow users to go to any link if they are authenticated, and the VGC links take the user to /search if they are not authenticated it takes them to /.

**Comment by KevinZheng0701** [comment]
Issue is fixed but I think we can do something about the default page, besides creating an account, we should also display games in slide format. So I think once someone login into their account, then the current page should be replaced by the display page or something like that. Let's leave this issue here until further improvements are made.
